apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xub0wplb7-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xub0wplb7-nodejs 
  name: xub0wplb7-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: xub0wplb7-nodejs 
